#!/bin/bash

cd $(dirname $0)

mkdir -p ssl

if [ ! -r ssl/localhost.cert.pem ]; then
    openssl req -x509 -out ssl/localhost.cert.pem -keyout ssl/localhost.key.pem -newkey rsa:2048 -nodes -sha256 -subj '/CN=localhost' -extensions EXT -config <(printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
fi
